// Generated by: gen
// TypeWriter: slice
// Directive: +gen on *Schema

package schema

import (
	"errors"
	"math/rand"
)

// Sort implementation is a modification of http://golang.org/pkg/sort/#Sort
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found at http://golang.org/LICENSE.

// SchemaSlice is a slice of type *Schema. Use it where you would use []*Schema.
type SchemaSlice []*Schema

// All verifies that all elements of SchemaSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv SchemaSlice) All(fn func(*Schema) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}

// Any verifies that one or more elements of SchemaSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv SchemaSlice) Any(fn func(*Schema) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}

// Count gives the number elements of SchemaSlice that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv SchemaSlice) Count(fn func(*Schema) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}

// DistinctBy returns a new SchemaSlice whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv SchemaSlice) DistinctBy(equal func(*Schema, *Schema) bool) (result SchemaSlice) {
Outer:
	for _, v := range rcv {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}

// First returns the first element that returns true for the passed func. Returns error if no elements return true. See: http://clipperhouse.github.io/gen/#First
func (rcv SchemaSlice) First(fn func(*Schema) bool) (result *Schema, err error) {
	for _, v := range rcv {
		if fn(v) {
			result = v
			return
		}
	}
	err = errors.New("no SchemaSlice elements return true for passed func")
	return
}

// GroupByString groups elements into a map keyed by string. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv SchemaSlice) GroupByString(fn func(*Schema) string) map[string]SchemaSlice {
	result := make(map[string]SchemaSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// Shuffle returns a shuffled copy of SchemaSlice, using a version of the Fisher-Yates shuffle. See: http://clipperhouse.github.io/gen/#Shuffle
func (rcv SchemaSlice) Shuffle() SchemaSlice {
	numItems := len(rcv)
	result := make(SchemaSlice, numItems)
	copy(result, rcv)
	for i := 0; i < numItems; i++ {
		r := i + rand.Intn(numItems-i)
		result[r], result[i] = result[i], result[r]
	}
	return result
}

// SortBy returns a new ordered SchemaSlice, determined by a func defining ‘less’. See: http://clipperhouse.github.io/gen/#SortBy
func (rcv SchemaSlice) SortBy(less func(*Schema, *Schema) bool) SchemaSlice {
	result := make(SchemaSlice, len(rcv))
	copy(result, rcv)
	// Switch to heapsort if depth of 2*ceil(lg(n+1)) is reached.
	n := len(result)
	maxDepth := 0
	for i := n; i > 0; i >>= 1 {
		maxDepth++
	}
	maxDepth *= 2
	quickSortSchemaSlice(result, less, 0, n, maxDepth)
	return result
}

// Where returns a new SchemaSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv SchemaSlice) Where(fn func(*Schema) bool) (result SchemaSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// Sort implementation based on http://golang.org/pkg/sort/#Sort, see top of this file

func swapSchemaSlice(rcv SchemaSlice, a, b int) {
	rcv[a], rcv[b] = rcv[b], rcv[a]
}

// Insertion sort
func insertionSortSchemaSlice(rcv SchemaSlice, less func(*Schema, *Schema) bool, a, b int) {
	for i := a + 1; i < b; i++ {
		for j := i; j > a && less(rcv[j], rcv[j-1]); j-- {
			swapSchemaSlice(rcv, j, j-1)
		}
	}
}

// siftDown implements the heap property on rcv[lo, hi).
// first is an offset into the array where the root of the heap lies.
func siftDownSchemaSlice(rcv SchemaSlice, less func(*Schema, *Schema) bool, lo, hi, first int) {
	root := lo
	for {
		child := 2*root + 1
		if child >= hi {
			break
		}
		if child+1 < hi && less(rcv[first+child], rcv[first+child+1]) {
			child++
		}
		if !less(rcv[first+root], rcv[first+child]) {
			return
		}
		swapSchemaSlice(rcv, first+root, first+child)
		root = child
	}
}

func heapSortSchemaSlice(rcv SchemaSlice, less func(*Schema, *Schema) bool, a, b int) {
	first := a
	lo := 0
	hi := b - a

	// Build heap with greatest element at top.
	for i := (hi - 1) / 2; i >= 0; i-- {
		siftDownSchemaSlice(rcv, less, i, hi, first)
	}

	// Pop elements, largest first, into end of rcv.
	for i := hi - 1; i >= 0; i-- {
		swapSchemaSlice(rcv, first, first+i)
		siftDownSchemaSlice(rcv, less, lo, i, first)
	}
}

// Quicksort, following Bentley and McIlroy,
// Engineering a Sort Function, SP&E November 1993.

// medianOfThree moves the median of the three values rcv[a], rcv[b], rcv[c] into rcv[a].
func medianOfThreeSchemaSlice(rcv SchemaSlice, less func(*Schema, *Schema) bool, a, b, c int) {
	m0 := b
	m1 := a
	m2 := c
	// bubble sort on 3 elements
	if less(rcv[m1], rcv[m0]) {
		swapSchemaSlice(rcv, m1, m0)
	}
	if less(rcv[m2], rcv[m1]) {
		swapSchemaSlice(rcv, m2, m1)
	}
	if less(rcv[m1], rcv[m0]) {
		swapSchemaSlice(rcv, m1, m0)
	}
	// now rcv[m0] <= rcv[m1] <= rcv[m2]
}

func swapRangeSchemaSlice(rcv SchemaSlice, a, b, n int) {
	for i := 0; i < n; i++ {
		swapSchemaSlice(rcv, a+i, b+i)
	}
}

func doPivotSchemaSlice(rcv SchemaSlice, less func(*Schema, *Schema) bool, lo, hi int) (midlo, midhi int) {
	m := lo + (hi-lo)/2 // Written like this to avoid integer overflow.
	if hi-lo > 40 {
		// Tukey's Ninther, median of three medians of three.
		s := (hi - lo) / 8
		medianOfThreeSchemaSlice(rcv, less, lo, lo+s, lo+2*s)
		medianOfThreeSchemaSlice(rcv, less, m, m-s, m+s)
		medianOfThreeSchemaSlice(rcv, less, hi-1, hi-1-s, hi-1-2*s)
	}
	medianOfThreeSchemaSlice(rcv, less, lo, m, hi-1)

	// Invariants are:
	//	rcv[lo] = pivot (set up by ChoosePivot)
	//	rcv[lo <= i < a] = pivot
	//	rcv[a <= i < b] < pivot
	//	rcv[b <= i < c] is unexamined
	//	rcv[c <= i < d] > pivot
	//	rcv[d <= i < hi] = pivot
	//
	// Once b meets c, can swap the "= pivot" sections
	// into the middle of the slice.
	pivot := lo
	a, b, c, d := lo+1, lo+1, hi, hi
	for {
		for b < c {
			if less(rcv[b], rcv[pivot]) { // rcv[b] < pivot
				b++
			} else if !less(rcv[pivot], rcv[b]) { // rcv[b] = pivot
				swapSchemaSlice(rcv, a, b)
				a++
				b++
			} else {
				break
			}
		}
		for b < c {
			if less(rcv[pivot], rcv[c-1]) { // rcv[c-1] > pivot
				c--
			} else if !less(rcv[c-1], rcv[pivot]) { // rcv[c-1] = pivot
				swapSchemaSlice(rcv, c-1, d-1)
				c--
				d--
			} else {
				break
			}
		}
		if b >= c {
			break
		}
		// rcv[b] > pivot; rcv[c-1] < pivot
		swapSchemaSlice(rcv, b, c-1)
		b++
		c--
	}

	min := func(a, b int) int {
		if a < b {
			return a
		}
		return b
	}

	n := min(b-a, a-lo)
	swapRangeSchemaSlice(rcv, lo, b-n, n)

	n = min(hi-d, d-c)
	swapRangeSchemaSlice(rcv, c, hi-n, n)

	return lo + b - a, hi - (d - c)
}

func quickSortSchemaSlice(rcv SchemaSlice, less func(*Schema, *Schema) bool, a, b, maxDepth int) {
	for b-a > 7 {
		if maxDepth == 0 {
			heapSortSchemaSlice(rcv, less, a, b)
			return
		}
		maxDepth--
		mlo, mhi := doPivotSchemaSlice(rcv, less, a, b)
		// Avoiding recursion on the larger subproblem guarantees
		// a stack depth of at most lg(b-a).
		if mlo-a < b-mhi {
			quickSortSchemaSlice(rcv, less, a, mlo, maxDepth)
			a = mhi // i.e., quickSortSchemaSlice(rcv, mhi, b)
		} else {
			quickSortSchemaSlice(rcv, less, mhi, b, maxDepth)
			b = mlo // i.e., quickSortSchemaSlice(rcv, a, mlo)
		}
	}
	if b-a > 1 {
		insertionSortSchemaSlice(rcv, less, a, b)
	}
}
